id: I3C37EF2B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:04:24+00:00'
last_modified: '2022-06-08T02:36:44.806407+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19021
  title: ཀཿཐོག་པ་དང་དེའི་ཆོས་བརྒྱུད་འཛིན་པའི་དགོན་པ་དང་རི་ཁྲོད་རྣམས་ཀྱི་ལོ་རྒྱུས་གནད་བསྡུས་འདོད་འབྱུང་དཔག་བསམ་ལྗོན་པའི་དབང་པོ།
    དེབ་གཉིས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9EC3:
      image_group_id: I8LS19023
      title: ''
      total_pages: 628
      order: 1
      base_file: 9EC3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
