id: opecha:P005371
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19021
  title: ཀཿཐོག་པ་དང་དེའི་ཆོས་བརྒྱུད་འཛིན་པའི་དགོན་པ་དང་རི་ཁྲོད་རྣམས་ཀྱི་ལོ་རྒྱུས་གནད་བསྡུས་འདོད་འབྱུང་དཔག་བསམ་ལྗོན་པའི་དབང་པོ།
    དེབ་གཉིས་པ།
  volume: ''
  author: ''
